import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Footer, Header, Providers } from "@/components";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Next-E-commerse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.className} bg-[#F9F4E2] min-h-screen`}>
        <div className="min-h-screen flex flex-col">
          <Providers>
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
